version: 2.1

jobs:
  build_and_push_image:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build and Push Docker Image
          command: |
            docker build -t my-image .
            docker push my-image

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_push_image